services:
  seminario-bd:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - data:/opt/oracle/oradata
      - ./scripts:/container-entrypoint-initdb.d/
      - ./Imagenes:/tmp/imagenes
    deploy:
      replicas: 1

  seminario-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./:/app
    environment:
      - ENV=development
      - DATABASE_URL=oracle+oracledb://seminario:seminario@seminario-bd:1521/?service_name=xe
      - SECRET_KEY=cualquiercosaquevosgusteparaserunasecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - seminario-bd
volumes:
  data:
