[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
pythonpath = .
testpaths = app tests
python_files = test*.py
python_classes = Test*
python_functions = test_*