version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - data:/opt/oracle/oradata
    deploy:
      replicas: 1

volumes:
  data:

# Usuario: system
# Contraseña: oracle
# Puerto: 1521
# Servicio: XE
# Conexión JDBC: jdbc:oracle:thin:@localhost:1521/XE